"""Updated model schema

Revision ID: c97b135772c0
Revises: f256c2e77bd0
Create Date: 2025-06-27 00:21:14.589269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97b135772c0'
down_revision: Union[str, Sequence[str], None] = 'f256c2e77bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet_posts', sa.Column('posted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet_posts', 'posted_at')
    # ### end Alembic commands ###
