


DATA_SCIENCE_TOPICS = [
    {
        "topic": "Basics of Python Programming",
        "subtopics": [
            "Python Basics",
            "Python Output/print function",
            "Python Data Types",
            "Python Variables",
            "Python comments",
            "Python Keywords and Identifiers",
            "Python User Input",
            "Python Type conversion",
            "Python Literals",
            "Python Operators + if-else + Loops",
            "Python Operators",
            "Python if-else",
            "Python Modules",
            "Python While Loop",
            "Python for loop",
            "Python Strings",
            "Introduction",
            "Solving Loop problems",
            "Break, continue, pass statement in loops",
            "Strings",
            "String indexing",
            "String slicing",
            "Edit and delete a string",
            "Operations on String",
            "Common String functions",
            "Time complexity",
            "Time Complexity (Efficiency in Programming and Orders of Growth)",
        ]
    },
    {
        "topic": "Python Data Types",
        "subtopics": [
            "Python Lists",
            "Introduction",
            "Array vs List",
            "How lists are stored in a memory",
            "Characteristics of Python List",
            "Code Example of Lists",
            "Create and access a list",
            "append(), extend(), insert()",
            "Edit items in a list",
            "Deleting items from a list",
            "Arithmetic, membership and loop operations on a List",
            "Various List functions",
            "List comprehension",
            "2 Ways to traverse a list",
            "Zip() function",
            "Python List can store any kind of objects",
            "Disadvantages of Python list",
            "Tuples + Set + Dictionary",
            "Tuple",
            "Create and access a tuple",
            "Can we edit and add items to a tuple?",
            "Deletion",
            "Operations on tuple",
            "Tuple functions",
            "List vs tuple",
            "Tuple unpacking",
            "Zip () on tuple",
            "Set",
            "Create and access a set",
            "Can we edit and add items to a set?",
            "Deletion",
            "Operations on set",
            "set functions",
            "Frozen set (immutable set)",
            "Set comprehension",
            "Dictionary",
            "Create dictionary",
            "Accessing items",
            "Add, remove, edit key-value pairs",
            "Operations on dictionary",
            "Dictionary functions",
            "Dictionary comprehension",
            "Zip() on dictionary",
            "Nested comprehension",
            "Python Functions",
            "Create function",
            "Arguments and parameters",
            "args and kwargs",
            "How to access documentation of a function",
            "How functions are executed in a memory",
            "Variable scope",
            "Nested functions with examples",
            "Functions are first class citizens",
            "Deletion of function",
            "Returning of function",
            "Advantages of functions",
            "Lambda functions",
            "Higher order functions",
            "map(), filter() reduce()"
        ]
    },
    {
        "topic": "Object Oriented Programming (OOP)",
        "subtopics": [
            "OOP Partl",
            "What is OOP?",
            "What are classes and Objects?",
            "Banking application coding",
            "Methods vs Functions",
            "Class diagram",
            "Magic/Dunder methods",
            "What is the true benefit of constructor?",
            "Concept of 'self'",
            "Create Fraction Class",
            "__str____add__,  sub",
            "OOP Part2",
            "mul__, __ truediv__",
            "How objects access attributes",
            "Attribute creation from outside of the class",
            "Reference Variables",
            "Mutability of Object",
            "Encapsulation",
            "Collection of objects",
            "Static variables and methods",
            "OOP Part3",
            "Class Relationship",
            "Aggregation and aggregation class diagram",
            "Inheritance and Inheritance class diagram",
            "Constructor example",
            "Method Overriding",
            "Super keyword",
            "Super constructor",
            "Practice questions on Inheritance",
            "Types of Inheritance (Single, Multilevel, Hierarchical, Multiple)",
            "Hybrid Inheritance",
            "Code example and diamond problem",
            "Polymorphism",
            "Method Overriding and Method Overloading",
            "Operator Overloading",
            "Abstraction",
            "What is Abstraction?",
            "Bank Example Hierarchy",
            "Abstract class",
            "Coding abstract class (BankApp Class)",
            "OOP Project"
        ]
    },
    {
        "topic": "Advanced Python:",
        "subtopics": [
            "File Handling + Serialization & Deserialization",
            "How File I/O is done",
            "Writing to a new text file",
            "What is open()?",
            "append()",
            "Writing many lines",
            "Saving a file",
            "Reading a file -> read() and readline()",
            "Using context manager -> with()",
            "Reading big file in chunks",
            "Seek and tell",
            "Working with Binary file",
            "Serialization and Deserialization",
            "JSON module -> dump() and load()",
            "Serialization and Deserialization of tuple, nested dictionary and custom object",
            "Pickling",
            "Pickle vs JSON",
            "Exception Handling",
            "Syntax Error with Examples",
            "Exception with Examples",
            "Why we need to handle Exception?",
            "Exception Handling (Try-Except-Else-Finally)",
            "Handling Specific Error",
            "Raise Exception",
            "Create custom Exception",
            "Decorators and Namespaces",
            "Namespaces",
            "Scope and LEGB rule",
            "Hands-on local, enclosing, global and built-in scope",
            "Decorators with Examples",
            "Iterators",
            "What are iterators",
            "What are iterables",
            "How for loop works in Python?",
            "Making your own for loop",
            "Create your own range function",
            "Practical example to use iterator",
            "Generator",
            "What is a generator?",
            "Why to use Generator?",
            "Yield vs Return",
            "Generator Expression",
            "Practical Examples",
            "Benefits of generator",
            "Resume Building",
            "GUI Development using Python",
            "GUI development using tkinter"
        ]
    },
    {
        "topic": "Numpy",
        "subtopics": [
            "Numpy Fundamentals",
            "Numpy Theory",
            "Numpy array",
            "Matrix in numpy",
            "Numpy array attributes",
            "Array operations",
            "Scalar and Vector operations",
            "Numpy array functions",
            "Dot product",
            "Log, exp, mean, median, std, prod, min, max, trigo, variance, ceil, floor, slicing, iteration",
            "Reshaping",
            "Stacking and splitting",
            "Advanced Numpy",
            "Numpy array vs Python List",
            "Advanced, Fancy and Boolean Indexing",
            "Broadcasting",
            "Mathematical operations in numpy",
            "Sigmoid in numpy",
            "Mean Squared Error in numpy",
            "Working with missing values",
            "Plotting graphs",
            "Numpy Tricks",
            "Various numpy functions like sort, append, concatenate, percentile, flip, Set functions, etc.",
            "Web Development using Flask",
            "What is Flask library",
            "Why to use Flask?",
            "Building login system and name entity recognition with API"
        ]
    },
    {
        "topic": "Pandas",
        "subtopics": [
            "Pandas Series",
            "What is Pandas?",
            "Introduction to Pandas Series",
            "Series Methods",
            "Series Math Methods",
            "Series with Python functionalities",
            "Boolean Indexing on Series",
            "Plotting graphs on series",
            "Pandas DataFrame",
            "Introduction Pandas DataFrame",
            "Creating DataFrame and read_csv()",
            "DataFrame attributes and methods",
            "Dataframe Math Methods",
            "Selecting cols and rows from dataframe",
            "Filtering a Dataframe",
            "Adding new columns",
            "Dataframe function - astype()",
            "Important DataFrame Methods",
            "Various DataFrame Methods",
            "Sort, index, reset_index, isnull, dropna, fillna, drop_duplicates, value_counts, apply, etc.",
            "API Development using Flask",
            "What is API?",
            "Building API using Flask",
            "Hands-on project"
        ]
    },
    {
        "topic": "Advanced Pandas",
        "subtopics": [
            "GroupBy Object",
            "What is GroupBy?",
            "Applying builtin aggregation fuctions on groupby objects",
            "GroupBy Attributes and Methods",
            "Hands-on on IPL dataset",
            "Merging, Joining, Concatenating",
            "Pandas concat method",
            "Merge and join methods",
            "Practical implementations",
            "Streamlit",
            "Introduction to Streamlit",
            "Features of Streamlit",
            "Benefits of Streamlit",
            "Flask vs Streamlit",
            "Mini-project on Indian Startup Funding Dataset using Streamlit - Part 1",
            "Pandas Case Study (Indian Startup Funding)",
            "Data Analysis on Indian Startup Funding Dataset and display results on the Dashboard made by Streamlit - Part 2",
            "Git:",
            "What is Git?",
            "What is VCS/SCM?",
            "Why Git/VCS is needed?",
            "Types of VCS",
            "Advantages",
            "How Git works?"
        ]
    },
    {
        "topic": "Advanced Pandas Continued",
        "subtopics": [
            "Installing git",
            "Creating and Cloning repo",
            "add, commit, add ., gitignore",
            "seeing commits (log -> oneline)",
            "Creating versions of a software",
            "Git and GitHub:",
            "Nonlinear Development (Branching)",
            "Merging branches",
            "Undoing changes",
            "Working with a remote repo",
            "MultiIndex Series and DataFrames",
            "About Multiindex objects",
            "Why to use Multiindex objects",
            "Stacking and unstacking",
            "Multiindex DataFrames",
            "Transpose Dataframes",
            "Swaplevel",
            "Long vs wide data",
            "Pandas-melt",
            "Vectorized String Operations | Datetime in Pandas",
            "Pivot table",
            "Agg functions",
            "Vectorized String operations",
            "Common functions",
            "Pandas Datetime",
            "Pandas Case Study – time Series analysis",
            "Pandas Case Study – Working with textual data"
        ]
    },
    {
        "topic": "Data Visualization",
        "subtopics": [
            "Plotting Using Matplotlib",
            "Get started with Matplotlib",
            "Plotting simple functions, labels, legends, multiple plots",
            "About scatter plots",
            "Bar chart",
            "Histogram",
            "Pie chart",
            "Changing styles of plots",
            "Advanced Matplotlib",
            "Colored Scatterplot",
            "Plot size, annotations",
            "Subplots",
            "3D plots",
            "Contour plots",
            "Heatmaps",
            "Pandas plot()",
            "Plotly (Express)",
            "About Plotly",
            "Disadvantages",
            "Introduction about Plotly Go, Plotly Express, Dash",
            "Hands-on Plotly"
        ]
    },
    {
        "topic": "Data Visualization Continued",
        "subtopics": [
            "Plotly Graph Objects (go)",
            "Plotly Dash",
            "Basic Introduction about Dash",
            "Making a COVID-19 dashboard using Plotly and Dash",
            "Deploying a Dash app on Heroku",
            "Project using Plotly",
            "Project using Indian Census Data with Geospatial indexing Dataset",
            "Plotting Using Seaborn- part 1",
            "Why seaborn?",
            "Seaborn roadmap",
            "Main Classification plotting",
            "Relational plots",
            "Distribution plots",
            "KDE plot",
            "Matrix plot",
            "Plotting Using Seaborn- Part 2",
            "Categorical Plots",
            "Stripplot",
            "Figure level function — catplot",
            "Swarmplot",
            "Categorical Distribution Plots",
            "Boxplot",
            "Violinplot",
            "Categorical Estimate Plot — for central tendency",
            "Barplot",
            "Pointplot",
            "Countplot",
            "Faceting",
            "Doubt - error bar issue",
            "Regression Plots",
            "Regplot",
            "Lmplot",
            "Residual Plot",
            "FacetGrid",
            "Pairplot and Pairgrid",
            "JointGrid and Jointplot",
            "Utility Function in Seabom - load_dataset",
            "Blog idea",
            "Open-Source Software – Part 1",
            "Open-Source Software – Part 1"
        ]
    },
    {
        "topic": "Data Analysis Process - Part1",
        "subtopics": [
            "Data Gathering | Data Analysis",
            "Data Analysis Process",
            "Import Data from various sources (CSV, excel, JSON, text, SQL)",
            "Export data in different file formats",
            "Gather Data through API or Web Scraping",
            "Data Assessing and Cleaning",
            "Data assessing",
            "Types of unclean data",
            "Write summary of data",
            "Types of Assessment",
            "Manual and Automatic Assessment",
            "Data Quality Dimension",
            "Data Cleaning",
            "ETL using AWS RDS",
            "Introduction about Extraction, transform and Load pipeline",
            "Fetch data from AWS",
            "Apply transformation on the data",
            "Upload transformed data into AWS RDS",
            "Advanced Web Scraping using Selenium",
            "Introduction to Selenium and Chromedriver",
            "Automated Web scraping on Smartprix website"
        ]
    },
    {
        "topic": "Data Analysis Process – Part 2",
        "subtopics": [
            "Data Cleaning Case Study – Smartphone dataset",
            "Quality issues",
            "Tidiness issues",
            "Data Cleaning",
            "Exploratory Data Analysis (EDA)",
            "Introduction to EDA",
            "Why EDA?",
            "Steps for EDA",
            "Univariate Analysis",
            "Bivariate Analysis",
            "Feature Engineering",
            "Data Cleaning – Part 2",
            "Data Cleaning on Smartphone Dataset – Continued",
            "EDA Case Study – Smartphone Dataset"
        ]
    },
    {
        "topic": "SQL Basics",
        "subtopics": [
            "Database Fundamentals",
            "Introduction to Data and Database",
            "CRUD operations",
            "Properties of database",
            "Types of Database",
            "DBMS",
            "Keys",
            "Cardinality of Relationship",
            "Drawbacks of Database",
            "SQL DDL Commands",
            "Xammp Software",
            "Types of SQL commands",
            "DDL commands",
            "Tableau – Olympics Dataset (Part 1)",
            "Download and Install Tableau",
            "Getting Started with Tableau Desktop",
            "Overview of Olympic datasets",
            "Create Dashboards using Tableau"
        ]
    },
    {
        "topic": "SQL Continued – Part 1",
        "subtopics": [
            "SQL DML commands",
            "MySQL workbench",
            "INSERT",
            "SELECT",
            "UPDATE",
            "DELETE",
            "Functions in SQL",
            "SQL Grouping and Sorting",
            "Sorting Data",
            "ORDER BY",
            "GROUP BY",
            "GROPU BY on multiple columns",
            "HAVING clause",
            "Practice on IPL Dataset",
            "Tableau – Part 2",
            "Tableau Basics",
            "Importing Data",
            "Measures and Dimensions",
            "Sheet, dashboard, story",
            "Levels of Granularity",
            "Different types of charts",
            "Datetime",
            "Hierarchical level of granularity",
            "Common filters",
            "Calculated fields and Table Calculations",
            "Working with Geographical columns",
            "Dashboard and Interactive filters",
            "Blending and Dual axis chart",
            "Connecting to a remote database"
        ]
    },
    {
        "topic": "SQL Continued - Part 2",
        "subtopics": [
            "SQL Joins",
            "Introduction to SQL joins",
            "Types of Joins (Cross, inner, left, right, full outer)",
            "SQL hands-on on joins",
            "SET operations",
            "SELF join",
            "Query execution order",
            "Practice questions",
            "SQL Case Study 1 – Zomato Dataset",
            "Understanding Dataset through diagram",
            "Solving SQL Questions on Zomato Dataset",
            "Subqueries in SQL",
            "What is Subquery",
            "Types of Subqueries",
            "Independent and Correlated subquery",
            "Making a Flight Dashboard using Python and SQL",
            "How to Connect MYSQL through Python",
            "Run SQL queries with Python",
            "Creating a dynamic dashboard with Streamlit on Flights dataset"
        ]
    },
    {
        "topic": "Advanced SQL",
        "subtopics": [
            "Window Functions in SQL",
            "What are Window functions?",
            "OVER(), RANK(), DENSE_RANK(), ROW_NUMBER(), FIRST_VALUE(), LAST_VALUE()",
            "Concept of Frames",
            "LAG(), LEAD()",
            "Windows Functions Part 2",
            "Ranking",
            "Cumulative sum and average",
            "Running average",
            "Percent of total",
            "Windows Functions Part 3",
            "Percent Change",
            "Quantiles/Percentiles",
            "Segmentation",
            "Cumulative Distribution",
            "Partition by multiple columns",
            "Data Cleaning using SQL | Laptop Dataset",
            "Basic level Data Cleaning and Data exploration using SQL",
            "Why to use SQL for Data Cleaning",
            "String Data types",
            "Wildcards",
            "String Functions",
            "Data Cleaning",
            "EDA using SQL | Laptop Dataset",
            "EDA on numerical and categorical columns",
            "Plotting",
            "Categorical – Categorical Analysis",
            "Numerical – Numerical Analysis"
        ]
    },
    {
        "topic": "Descriptive Statistics",
        "subtopics": [
            "Descriptive Statistics Part 1",
            "What is Statistics?",
            "Types of Statistics",
            "Population vs Sample",
            "Types of Data",
            "Measures of central tendency",
            "Measure of Dispersion",
            "Coefficient of variation",
            "Graphs for Univariate Analysis",
            "Frequency Distribution table",
            "Graphs for bivariate Analysis",
            "Categorical – Categorical Analysis",
            "Numerical – Numerical Analysis",
            "Categorical – Numerical Analysis",
            "Datetime in SQL",
            "Remaining topics of EDA using SQL (numerical - categorical,missing values, ppi, price_bracket, one hot encoding)",
            "Temporal Data types",
            "Creating and Populating Temporal Tables",
            "DATETIME Functions",
            "Datetime Formatting"
        ]
    },
    {
        "topic": "Descriptive Statistics continued",
        "subtopics": [
            "Type Conversation",
            "DATETIME Arithmetic",
            "TIMESTAMP VS DATETIME",
            "Case Study – Flights",
            "Descriptive Statistics part 2",
            "Quantiles and Percentiles",
            "Five Number Summary",
            "Boxplots",
            "Scatterplots",
            "Covariance",
            "Correlation",
            "Correlation vs Causation",
            "Visualizing multiple variables",
            "Probability Distribution Functions (PDF, CDF, PMF)",
            "Random Variables",
            "Probability Distributions",
            "Probability Distribution Functions and its types",
            "Probability Mass Function (PMF)",
            "Cumulative Distribution Function (CDF) of PMF",
            "Probability Density Function (PDF)",
            "Density Estimation",
            "Parametric and Non-parametric Density Estimation",
            "Kernel Density Estimate (KDE)",
            "Cumulative Distribution Function (CDF) of PDF.",
            "SQL Datetime Case Study on Flights Dataset",
            "Database Design | SQL Data Types | Database Normalization",
            "Different SQL Datatypes (Numeric, Text, Datetime, Misc)",
            "Database Normalization",
            "ER Diagram"
        ]
    },
    {
        "topic": "Probability Distributions",
        "subtopics": [
            "Normal Distribution",
            "How to use PDF in Data Science?",
            "2D density plots",
            "Normal Distribution (importance, equation, parameter, intuition)",
            "Standard Normal Variate (importance, z-table, empirical rule)",
            "Properties of Normal Distribution",
            "Skewness",
            "CDF of Normal Distribution",
            "Use of Normal Distribution in Data Science",
            "Non-Gaussian Probability Distributions",
            "Kurtosis",
            "Excess Kurtosis and Types of kurtosis",
            "QQ plot",
            "Uniform Distribution",
            "Log-normal distribution",
            "Pareto Distribution",
            "Transformations",
            "Mathematical Transformation",
            "Function Transformer",
            "Log Transform",
            "Reciprocal Transform / Square or sqrt Transform",
            "Power Transformer",
            "Box-Cox Transform",
            "Yeo-Johnson Transformation",
            "views and User Defined Functions in SQL",
            "What are views?",
            "Types of views",
            "User Defined Functions (Syntax, Examples, Benefits)",
            "Transactions and Stored Procedures",
            "Stored Procedures",
            "Benefits of using stored procedures",
            "Transactions (Commit, rollback, savepoint)",
            "ACID properties of a Transaction"
        ]
    },
    {
        "topic": "Inferential Statistics",
        "subtopics": [
            "Central Limit Theorem",
            "Bernouli Distribution",
            "Binomial Distribution",
            "PDF formula",
            "Graph of PDF",
            "Examples",
            "Criteria",
            "Application in Data Science",
            "Sampling Distribution",
            "Intuition of Central Limit Theorem (CLT)",
            "CLT in code",
            "Case study",
            "Assumptions of making samples",
            "Central Limit Theorem Proof",
            "Confidence Intervals",
            "Population vs Sample",
            "Parameter vs Estimate",
            "Point Estimate",
            "Confidence Interval",
            "Ways to calculate CI",
            "Applications of CI",
            "Assumptions of z-procedure",
            "Formula and Intuition of z-procedure",
            "Interpreting CI",
            "T-procedure and t-distribution",
            "Confidence Intervals in code"
        ]
    },
    {
        "topic": "Hypothesis Testing",
        "subtopics": [
            "Hypothesis Testing (Part 1)",
            "Key idea of hypothesis testing",
            "Null and alternate hypothesis",
            "Steps in Hypothesis testing",
            "Performing z-test",
            "Rejection region and Significance level",
            "Type-1 error and Type-2 Error",
            "One tailed vs. two tailed test",
            "Applications of Hypothesis Testing",
            "Hypothesis Testing in Machine Learning",
            "Hypothesis Testing (Part 2) | p-value and t-tests",
            "What is p-value?",
            "Interpreting p-value",
            "P-value in the context of z-test",
            "T-test",
            "Types of t-test",
            "Single sample t-Test",
            "Independent 2-sample t-Test",
            "Paired 2 sample t-Test",
            "Code examples of all of the above",
            "Chi-square test",
            "Chi – square distribution (Definition and Properties)",
            "Chi-square test",
            "Goodness of fit test (Steps, Assumptions, Examples)",
            "Test for Independence (Steps, Assumptions, Examples)",
            "Applications in machine learning",
            "ANOVA",
            "Introduction",
            "F-distribution",
            "One-way ANOVA",
            "Steps",
            "Geometric Intuition",
            "Assumptions",
            "Python Example",
            "Post – Hoc test",
            "Why t-test is not used for more than 3 categories?",
            "Applications in Machine Learning"
        ]
    },
    {
        "topic": "Linear Algebra",
        "subtopics": [
            "Tensors | Linear Algebra part 1(a)",
            "What are tensors?",
            "0D, 1D and 2D Tensors",
            "Nd tensors",
            "Rank, axes and shape",
            "Example of 1D, 2D, 3D, 4D, 5D tensors",
            "Vectors | Linear Algebra part 1(b)",
            "What is Linear Algebra?",
            "What are Vectors?",
            "Vector example in ML",
            "Row and Column vector",
            "Distance from Origin",
            "Euclidean Distance",
            "Scalar Addition/Subtraction (Shifting)",
            "Scalar Multiplication/Division [Scaling]",
            "Vector Addition/Subtraction",
            "Dot product",
            "Angle between 2 vectors",
            "Equation of a Hyperplane",
            "Linear Algebra Part 2 | Matrices (computation)",
            "What are matrices?",
            "Types of Matrices",
            "Matrix Equality",
            "Scalar Operation",
            "Matrix Addition, Subtraction, multiplication",
            "Transpose of a Matrix",
            "Determinant",
            "Minor",
            "Cofactor",
            "Adjoint",
            "Inverse of Matrix",
            "Solving a system of Linear Equations",
            "Linear Algebra Part 3 | Matrices (Intuition)",
            "Basis vector",
            "Linear Transformations",
            "Linear Transformation in 3D",
            "Matrix Multiplication as Composition",
            "Test of Commutative Law",
            "Determinant and Inverse",
            "Transformation for non-square matrix?",
            "Why only square matrix has inverse?",
            "Why inverse is possible for non-singular matrices only?"
        ]
    },
    {
        "topic": "Linear Regression",
        "subtopics": [
            "Introduction to Machine Learning",
            "About Machine Learning (History and Definition)",
            "Types of ML",
            "Supervised Machine Learning",
            "Unsupervised Machine Learning",
            "Semi supervised Machine Learning",
            "Reinforcement Learning",
            "Batch/Offline Machine Learning",
            "Disadvantages of Batch learning",
            "Online Machine Learning",
            "Importance",
            "When to use and how to use",
            "Learning Rate",
            "Out of core learning",
            "Disadvantages",
            "Batch vs Online learning",
            "Instance based learning",
            "model-based learning",
            "Instance vs model-based learning",
            "Challenges in ML",
            "Data collection",
            "Insufficient/Labelled data",
            "Non-representative data",
            "Poor quality data",
            "Irrelevant features",
            "Overfitting and Underfitting",
            "Offline learning",
            "Cost",
            "Machine Learning Development Life-cycle",
            "Different Job roles in Data Science",
            "Framing a ML problem | How to plan a Data Science project",
            "Simple Linear regression",
            "Introduction and Types of Linear Regression",
            "Simple Linear Regression",
            "Intuition of simple linear regression",
            "Code example",
            "How to find m and b?",
            "Simple Linear Regression model code from scratch",
            "Regression Metrics",
            "MAE",
            "MSE",
            "RMSE",
            "R2 score",
            "Adjusted R2 score",
            "Multiple Linear Regression",
            "Introduction to Multiple Linear Regression (MLR)",
            "Code of MLR",
            "Mathematical Formulation of MLR",
            "Error function of MLR",
            "Minimizing error",
            "Error function continued",
            "Code from scratch",
            "Optimization the Big Picture",
            "Mathematical Functions",
            "Multivariable Functions",
            "Parameters in a Function",
            "ML models as Mathematical Function",
            "Parametric Vs Non-Parametric ML models",
            "Linear Regression as a Parametric ML model",
            "Loss Function",
            "How to select a good Loss Function?",
            "Calculating Parameters from a Loss Function",
            "Convex And Non-Convex Loss Functions",
            "Gradient Descent",
            "Gradient Descent with multiple Parameters",
            "Problems faced in Optimization",
            "Other optimization techniques",
            "Differential Calculus",
            "What is differentiation?",
            "Derivative of a constant",
            "Cheatsheet",
            "Power Rule",
            "Sum Rule",
            "Product Rule",
            "Quotient Rule",
            "Chain Rule",
            "Partial Differentiation",
            "Higher Order Derivatives",
            "Matrix Differentiation"
        ]
    },
    {
        "topic": "Gradient Descent",
        "subtopics": [
            "Gradient descent from scratch",
            "What is Gradient Descent?",
            "Intuition",
            "Mathematical Formulation",
            "Code from scratch",
            "Visualization 1",
            "Effect of Learning Rate",
            "Adding m into the equation",
            "Effect of Loss function",
            "Effect of Data",
            "Batch Gradient Descent",
            "Types of Gradient Descent",
            "Mathematical formulation",
            "Code from scratch",
            " Stochastic Gradient Descent",
            "Problems with Batch GD",
            "Stochastic GD",
            "Code from scratch",
            "Time comparison",
            "Visualization",
            "When to use stochastic GD",
            "Learning schedules",
            "Sklearn documentation",
            "Mini-batch Gradient Descent",
            "Introduction",
            "Code",
            "Visualization"
        ]
    },
    {
        "topic": "Regression Analysis",
        "subtopics": [
            "Regression Analysis (Part 1)",
            "What is Regression Analysis?",
            "Why Regression Analysis is required?",
            "What’s the Statistic connection with Regression analysis?",
            "Inference vs Prediction",
            "Statsmodel Linear Regression",
            "TSS, RSS, and ESS",
            "Degree of freedom",
            "F-statistic and Prob(F-statistic)",
            "Regression Analysis (Part 2)",
            "F -test for overall significance",
            "R-squared (Goodness of fit)",
            "Adjusted R-squared",
            "T – Statistic",
            "Confidence Intervals for Coefficients",
            "Polynomial Regression",
            "Why we need Polynomial Regression?",
            "Formulation of Polynomial Regression",
            "Polynomial Regression in python",
            "Assumptions of Linear Regression",
            "Assumptions of Linear Regression",
            "Linearity",
            "Normality of Residuals",
            "Homoscedasticity",
            "No Autocorrelation",
            "No or little Multicollinearity",
            "What happen when these assumptions failed?",
            "How to check each of these assumptions?",
            "What to do when an assumption fails?",
            "Standard Error",
            "Multicollinearity",
            "What is multicollinearity?",
            "When is Multicollinearity bad?",
            "Multicollinearity (Mathematically)",
            "Perfect and non-perfect Multicollinearity",
            "Types of multicollinearity",
            "How to detect Multicollinearity",
            "Correlation",
            "VIF (Variance Inflation Factor)",
            "Condition Number",
            "How to remove Multicollinearity"
        ]
    },
    {
        "topic": "Feature Selection",
        "subtopics": [
            "feature Selection Part 1",
            "What is Feature Selection?",
            "Why to do Feature Selection?",
            "Types of Feature Selection",
            "Filter based Feature Selection",
            "Duplicate Features",
            "Variance Threshold",
            "Correlation",
            "ANOVA",
            "Chi-Square",
            "Advantages and Disadvantages",
            "Feature Selection Part 2",
            "Wrapper method",
            "Types of wrapper method",
            "Exhaustive Feature Selection/Best Subset Selection",
            "Sequential Backward Selection/Elimination",
            "Sequential Forward Selection",
            "Advantages and Disadvantages",
            "Feature Selection part 3",
            "Embedded Methods",
            "Linear Regression",
            "Tree based models",
            "Regularized Models",
            "Recursive Feature Elimination",
            "Advantages and Disadvantages"
        ]
    },
    {
        "topic": "Regularization",
        "subtopics": [
            "Regularization Part 1 | Bias-Variance Tradeoff",
            "Why we need to study Bias and Variance",
            "Expected Value and Variance",
            "Bias and Variance Mathematically",
            "Regularization Part 1 | What is Regularization",
            "Bias Variance Decomposition",
            "Diagram",
            "Analogy",
            "Code Example",
            "What is Regularization?",
            "When to use Regularization?",
            "Ridge Regression Part 1",
            "Types of Regularization",
            "Geometric Intuition",
            "Sklearn Implementation",
            "Ridge Regression Part 2",
            "Ridge Regression for 2D data",
            "Ridge Regression for nD data",
            "Code from scratch",
            "Ridge Regression Part 3",
            "Ridge regression using Gradient Descent",
            "Ridge Regression Part 4",
            "5 Key Understandings",
            "How do the coefficients get affected?",
            "Higher values are impacted more",
            "Bias variance tradeoff",
            "Contour plot",
            "Why is it called Ridge?",
            "Lasso Regression",
            "Intuition",
            "Code example",
            "Lasso regression key points",
            "Why Lasso Regression creates Sparsity?",
            "ElasticNet Regression",
            "Intuition",
            "Code example"
        ]
    },
    {
        "topic": "K Nearest Neighbors",
        "subtopics": [
            "K nearest Neighbors Part 1",
            "KNN intuition",
            "Code Example",
            "How to select K?",
            "Decision Surface",
            "Overfitting and Underfitting in KNN",
            "Limitations of KNN",
            "coding K nearest Neighbors from scratch",
            "How to draw Decision Boundary for Classification problems",
            "Advanced KNN Part 2",
            "KNN Regressor",
            "Hyperparameters",
            "Weighted KNN",
            "Types of Distances (Euclidean and Manhattan)",
            "Space and Time Complexity",
            "KD-Tree",
            "Classification Metrics Part 1",
            "Accuracy",
            "Accuracy of multi-classification problems",
            "How much accuracy is good?",
            "Problem with accuracy",
            "Confusion matrix",
            "Type 1 error",
            "Type 2 error",
            "Confusion matrix of multi-classification problems",
            "When accuracy is misleading",
            "Classification Metrics Part 2",
            "Precision",
            "Recall",
            "F1 score",
            "Multi class Precision and Recall",
            "Multi class F1 score"
        ]
    },
    {
        "topic": "PCA",
        "subtopics": [
            "Curse of Dimensionality",
            "PCA part 1",
            "Introduction",
            "Geometric Intuition of PCA",
            "Why is Variance important?",
            "PCA part 2",
            "Mathematical Problem formulation",
            "What is covariance and covariance matrix?",
            "Matrices as Linear Transformation",
            "EigenVectors and Eigenvalues",
            "Step by step solution of PCA",
            "How to transform points?",
            "PCA step-by-step code in python",
            "PCA Part 3",
            "Practical example on MNIST dataset",
            "PCA demo with sklearn",
            "Visualization",
            "What is explained variance",
            "Find optimum number of Principal components",
            "When PCA does not work?",
            "Eigen vectors and Eigen Values",
            "What are Matrices?",
            "What are Eigen Vectors and Eigen Values?",
            "Intuition – Axis of rotation",
            "How to calculate Eigen Vectors and Eigen Values",
            "Properties",
            "Eigen Vectors in PCA",
            "Eigen Decomposition and PCA variants",
            "Types of PCA variants",
            "What are some special matrices?",
            "Diagonal Matrix",
            "Orthogonal Matrix",
            "Symmetric Matrix",
            "Matrix as Linear Transformation Visualization tool",
            "Matrix Composition",
            "Matrix Decomposition",
            "Eigen decomposition",
            "Eigen decomposition of Symmetric Matrix (Spectral Decomposition)",
            "Advantages of Eigen decomposition",
            "Kernel PCA",
            "Code example of Kernel PCA",
            "eigen Singular Value Decomposition (SVD)",
            "Intuition of Non-Square Matrix",
            "Rectangular Diagonal Matrix",
            "What is SVD",
            "Applications of SVD",
            "SVD - The intuition of the mathematical equation",
            "Relationship with Eigen Decomposition",
            "Geometric Intuition of SVD",
            "How to calculate SVD",
            "SVD in PCA"
        ]
    },
    {
        "topic": "Model Evaluation & Selection",
        "subtopics": [
            "ROC Curve in Machine Learning",
            "ROC AUC Curve and it’s requirements",
            "Confusion matrix",
            "True Positive Rate (TPR)",
            "False Positive Rate (FPR)",
            "Different cases of TPR & FPR",
            "Cross Validation",
            "Why do we need Cross Validation?",
            "Hold-out approach",
            "Problem with Hold-out approach",
            "Why is the Hold-out approach used?",
            "Cross Validation",
            "Leave One Out Cross Validation (LOOCV)",
            "Advantages",
            "Disadvantages",
            "When to use",
            "K-Fold Cross Validation",
            "Advantages",
            "Disadvantages",
            "When to use",
            "Stratified K-Fold CV",
            "Data Leakage",
            "What is it and what is the problem",
            "Ways in which Data Leakage can occur",
            "How to detect",
            "How to remove Data Leakage",
            "Validation set",
            "Hyperparameter Tuning",
            "Parameter vs Hyperparameter",
            "Why the word “hyper” in the term",
            "Requirements",
            "Grid Search CV",
            "Randomized Search CV",
            "Can this be improved?"
        ]
    },
    {
        "topic": "Naive Bayse",
        "subtopics": [
            "Crash course on Probability Part 1",
            "5 important terms in Probability",
            "Random Experiment",
            "Trials",
            "Outcome",
            "Sample Space",
            "Event",
            "Some examples of these terms",
            "Types of events",
            "What is probability",
            "Empirical vs Theoretical probability",
            "Random variable",
            "Probability distribution of random variable",
            "Mean of 2 random variable",
            "Variance of Random variable",
            "Crash course on Probability Part 2",
            "Venn diagrams",
            "Contingency table",
            "Joint probability",
            "Marginal probability",
            "Conditional probability",
            "Intuition of Conditional Probability",
            "Independent vs Dependent vs Mutually Exclusive Events",
            "Bayes Theorem",
            " Naive Bayes",
            "Intuition",
            "Mathematical formulation",
            "How Naive Bayes handles numerical data",
            "What if data is not Gaussian",
            "Naive Bayse on Textual data",
            "Naive Bayes",
            "What is underflow in computing",
            "Log Probabilities",
            "Laplace Additive Smoothing",
            "Bias Variance Trade off",
            "Types",
            "Gaussian Naive Bayes",
            "Categorical Naive Bayes",
            "Multinomial Naive Bayes",
            "Naive Bayes",
            "Probability Distribution related to Naive Bayes",
            "Bernoulli Distribution",
            "Binomial Distribution",
            "Categorical distribution / Multinoulli distribution",
            "Multinomial Distribution",
            "Why do we need these distributions?",
            "Categorical Naive Bayes",
            "Bernoulli Naive Bayes",
            "Multinomial Naive Bayes",
            "Out of Core Naive Bayes",
            "End to End Project | Email Spam Classifier"
        ]
    },
    {
        "topic": "Logistics Regression",
        "subtopics": [
            " Logistic Regression",
            "Introduction",
            "Some Basic Geometry",
            "Classification Problem",
            "Basic Algorithm",
            "Updation in Basic Algorithm",
            "Sigmoid Function",
            "Maximum Likelihood",
            "Log Loss",
            "Gradient Descent",
            "summary",
            "Multiclass Classification using Logistic Regression",
            "What is Multiclass Classification",
            "How Logistic Regression handles Multiclass Classification Problems.",
            "One vs Rest (OVR) Approach",
            "Intuition",
            "Code",
            "SoftMax Logistic Regression Approach",
            "SoftMax Function",
            "Code",
            "When to use what?",
            "Tasks",
            "Maximum Likelihood Estimation",
            "Recap",
            "Some Examples",
            "Example 1 - Coin Toss",
            "Example 2 - Drawing balls from bag",
            "Example 3 - Normal Distribution",
            "Probability Vs Likelihood",
            "Maximum Likelihood Estimation",
            "MLE for Normal Distribution",
            "MLE in Machine Learning",
            "MLE in Logistic Regression",
            "Some Important Questions",
            "Logistic Regression",
            "Maximum Likelihood in Logistic Regression",
            "FAQ on MAE (Maximum Likelihood Estimation)",
            "Is MLE a general concept applicable to all ML algorithms?",
            "How is MLE related to the concept of loss functions?",
            "Why does the loss function exist, why don’t we maximize likelihood?",
            "Why study about maximum likelihood at all?",
            "An interesting task for you",
            "Assumptions of Logistics Regression",
            "Odds and Log(Odds)",
            "Another interpretation of Logistic Regression",
            "Polynomial Features",
            "Regularization in Logistic Regression",
            "Logistic Regression Hyperparameters"
        ]
    },
    {
        "topic": "Support Vector Machines (SVM)",
        "subtopics": [
            "SVM Part 1 - Hard Margin SVM",
            "Introduction",
            "Maximum Margin Classifier",
            "Support Vectors",
            "Mathematical Formulation",
            "How to solve this?",
            "Prediction",
            "Coding Example",
            "Problems with Hard Margin SVM",
            "SVM Part 2 | Soft Margin SVM",
            "Problems with Hard Margin SVM",
            "Slack Variable",
            "Soft Margin SVM",
            "Introduction of C",
            "Bias-Variance Trade Off",
            "Code Example",
            "Relation with Logistic Regression",
            "Constrained Optimization Problem",
            "Problem with SVC",
            "Kernel’s Intuition",
            "Coding examples of Kernel",
            "Types of Kernels",
            "Why is it called Trick?",
            "Mathematics if SVM",
            "SVM Dual Problem",
            "SVM in n Dimensions",
            "Constrained Optimization Problems",
            "Karush Kuhn Tucker Conditions",
            "Concept of Duality",
            "SVM Dual Problem",
            "Dual Problem Derivation",
            "Observations",
            "Maths Behind SVM Kernels",
            "SVM Dual Formulation",
            "The Similarity Perspective",
            "Kernel SVM",
            "Polynomial Kernel",
            "Trick",
            "What about the other Polynomial terms",
            "RBF Kernel",
            "Local Decision Boundary",
            "Effect of Gamma",
            "Relationship Between RBF and Polynomial ... К",
            "Custom Kernels",
            "String kernel",
            "Chi-square kernel",
            "Intersection kernel",
            "Hellinger's kernel",
            "Radial basis function network (RBFN) kernel",
            "Spectral kernel"
        ]
    },
    {
        "topic": "Feature Engineering",
        "subtopics": [
            "Handling Missing Values Part - 1",
            "Feature Engineering",
            "Feature Transformation",
            "Feature Construction",
            "Feature Extraction",
            "Feature Selection",
            "Types of Missing Values",
            "Missing Completely at random",
            "Missing at Random",
            "Missing Not at Random",
            "Techniques for Handling Missing Values",
            "Removing Missing Values",
            "Imputation",
            "Complete Case Analysis",
            "Handling Missing Data",
            "Univariate Imputation - Numerical Data",
            "Mean Imputation",
            "Median Imputation",
            "Univariate Imputation - Arbitrary Value & End Distribution Value",
            "Univariate Imputation - Categorical Data",
            "Mode Imputation",
            "Missing Category Imputation",
            "Univariate Imputation - Random (Numerical + Categorical)",
            "Missing Indicator",
            "Handling Missing Data - Multivariate Imputation",
            "KNN Imputer",
            "Steps in KNN Imputation",
            "Advantages and Disadvantages in KNN Imputation",
            "Iterative Imputer",
            "MICE",
            "When To Use",
            "Advantages and Disadvantages",
            "Demonstration of MICE algorithm",
            "Steps involved in Iterative Imputer",
            "Important parameter in Iterative Imputer",
            "Missing Value Imputation",
            "Understanding the Impact: Influence on models; Types of missing values",
            "Techniques for Imputation: Mean/Median/Mode; K-NN; Regression; MICE",
            "Outlier Detection and Removal",
            "Understanding Outliers: Definition; Impact on models",
            "Techniques for Detection: Z-score; IQR; DBSCAN",
            "Removal Strategies: Truncation; Transformation",
            "Feature Scaling",
            "Importance in Modeling: Effects on algorithms; Influence on performance",
            "Common Methods: Min-Max; Standardization; Robust Scaler",
            "Feature Encoding",
            "Categorical Encoding: One-hot; Label; Binary; Target",
            "Handling Ordinal Variables: Mapping; Custom encoding strategies",
            "Sklearn Transformers",
            "Utilization in Pipelines: Building preprocessing pipelines; Combining steps",
            "Custom Transformers: Creating and implementing",
            "Commonly Used Transformers: Overview and application",
            "Project: Applying Preprocessing Techniques",
            "Data Exploration: Understanding dataset and features",
            "Applying Learned Techniques: Hands-on application",
            "Model Building and Evaluation: Building and evaluating models",
            "Encoding Categorical Features - 1",
            "Feature Engineering Roadmap",
            "What is Feature Encoding",
            "Ordinal Encoding",
            "Code examples in Python",
            "Handling Rare Categories",
            "Label Encoding",
            "Code Example using Sklearn LabelEncoder",
            "One Hot Encoding",
            "Code Examples using Sklearn OneHotEncoder",
            "Handling unknown Category",
            "LabelBinarizer",
            "Sklearn ColumnTransformer & Pipeline",
            "Sklearn Deep Dive",
            "Encoding Categorical Features",
            " Discretization",
            "Discretization",
            " Handling Missing Data",
            "Handling Missing Data",
            "Handling Missing Data",
            "Feature Scaling"
        ]
    },
    {
        "topic": "Decision Trees",
        "subtopics": [
            " Decision Tree",
            "Introduction",
            "Intuition behind DT",
            "Terminology in Decision Tree",
            "The CART Algorithm - Classification",
            "Splitting Categorical Features",
            "Splitting Numerical Features",
            "Understanding Gini Impurity?",
            "Geometric Intuition of DT",
            "Decision Tree",
            "CART for Regression",
            "Geometric Intuition of CART",
            "How Prediction is Done",
            "Advantages & Disadvantages of DT",
            "Project Discussion - Real Estate",
            "Decision Tree",
            "Feature Importance",
            "The Problem of Overfitting",
            "Why Overfitting happens",
            "Unnecessary nodes",
            "Pruning & its types",
            "Pre-pruning",
            "Post Pruning",
            "Cost Complexity Pruning",
            "Decision Tree Visualization",
            "dtreeviz Demo - Coding"
        ]
    },
    {
        "topic": "Ensemble Methods - Introduction",
        "subtopics": [
            "Introduction to Ensemble Learning",
            "Intuition",
            "Types of Ensemble Learning",
            "Why it works?",
            "Benefits of Ensemble",
            "When to use Ensemble",
            "Bagging Part 1 - Introduction",
            "Core Idea",
            "Why use Bagging?",
            "When to use Bagging?",
            "Code Demo",
            "Bagging Part 2 - Classifier",
            "Intuition through Demo app",
            "Code Demo",
            "Bagging Part 3 - Regressor",
            "Core Idea",
            "Intuition through demo web app",
            "Code Demo",
            "Random Forest : ",
            "Introduction to Random Forest",
            "Bagging",
            "Random Forest Intuition",
            "Why Random Forest Works?",
            "Bagging vs. Random Forest",
            "Feature Importance",
            "Random Forest : ",
            "Why Ensemble Techniques work?",
            "Random Forest Hyperparameters",
            "OOB Score",
            "Extremely Randomized Trees",
            "Advantages and Disadvantages of Random Forest"
        ]
    },
    {
        "topic": "Gradient Boosting",
        "subtopics": [
            "Gradient Boosting : ",
            "Boosting",
            "What is Gradient Boosting",
            "How",
            "What",
            "Why",
            "Gradient Boosting : ",
            "How Gradient Boosting works?",
            "Intuition of Gradient Boosting",
            "Function Space vs. Parameter Space",
            "Direction of Loss Minimization",
            "How to update the function",
            "Iterate",
            "Another perspective of Gradient Boosting",
            "Difference between Gradient Boosting and Gradient Descent",
            "Gradient Boosting :  (Classification - 1)",
            "Classification vs. Regression",
            "Prediction",
            "Gradient Boosting for Classification - 2 | Geometric Intuition",
            "Geometric Intuition",
            "Gradient Boosting for Classification - 3 | Math Formulation",
            "Step 0 : Loss Function",
            "Step 1 : Minimise Loss Function to get F0(x)",
            "Step 2 :",
            "Pseudo Residuals",
            "Training Regression Tree",
            "Compute Lambda for all leaf nodes",
            "Update the Model",
            "Step 3 : Final Model",
            "Log(odds) vs Probability"
        ]
    },
    {
        "topic": "Capstone Project:",
        "subtopics": [
            " Capstone Project | Data Gathering",
            "Project overview in details",
            "Gather data for the project",
            "Details of the data",
            "Capstone Project | Data Cleaning",
            "Merging House and Flats Data",
            "Basic Level Data Cleaning",
            "Capstone Project | Feature Engineering",
            "Feature Engineering on Columns:",
            "additionalRoom",
            "areaWithType",
            "agePossession",
            "furnishDetails",
            "features : luxury Score",
            " on Capstone Project | EDA",
            "Univariate Analysis",
            "PandasProfiling",
            "Multivariate Analysis",
            "Capstone Project | Outlier Detection and Removal",
            "Outlier Detection And Removal",
            "Capstone Project | Missing Value Imputation",
            "Outlier Detection and Removal on area and bedroom",
            "Missing Value Imputation",
            "Feature Selection",
            "Correlation Technique",
            "Random Forest Feature Importance",
            "Gradient Boosting Feature Importance",
            "Permutation Importance",
            "LASSO",
            "Recursive Feature Elimination",
            "Linear Regression with Weights",
            "SHAP (Explainable AI)",
            "Linear Regression - Base Model",
            "One-Hot Encoding",
            "Transformation",
            "Pipeline for Linear Regression",
            "SVR",
            "Model Selection & Productionalization",
            "Price Prediction Pipeline",
            "Encoding Selection",
            "Ordinal Encoding",
            "OHE",
            "OHE with PCA",
            "Target Encoding",
            "Model Selection",
            "Price Prediction Web Interface -Streamlit",
            "Building the Analytics Module",
            "geo map",
            "word cloud amenities",
            "scatterplot -> area vs price",
            "pie chart bhk filter by sector",
            "side by side boxplot bedroom price",
            "distplot of price of flat and house",
            "Building the Recommender System",
            "Recommender System using TopFacilities",
            "Recommender System using Price Details",
            "Recommender System using LocationAdvantages",
            "Building the Recommender System Part 2",
            "Evaluating Recommendation Results",
            "Web Interface for Recommendation (Streamlit)",
            "Building the Insights Module",
            "Deploying the application on AWS"
        ]
    },
    {
        "topic": "XGBoost (Extreme Gradient Boosting)",
        "subtopics": [
            "Introduction to XGBoost",
            "Introduction",
            "Features",
            "Performance",
            "Speed",
            "Flexibility",
            "XGBoost for Regression",
            "Regression Problem Statement",
            "Step-by-Step Mathematical Calculation",
            "XGBoost for Classification",
            "Classification Problem Statement",
            "Step-by-Step Mathematical Calculation",
            "The Complete Maths of XGBoost",
            "Prerequisite & Disclaimer",
            "Boosting as an Additive Model",
            "XGBoost Loss Function",
            "Deriving Objective Function",
            "Problem With Objective Function and Solution",
            "The Taylor series",
            "Applying Taylor Series",
            "Simplification",
            "Output Value for Regression",
            "Output Value for Classification",
            "Derivation of Similarity Score",
            "Final Calculation of Similarity Score"
        ]
    },
    {
        "topic": "MLOps Curriculum",
        "subtopics": [
            "Introduction to MLOps and ML-DLC",
            "Introduction to MLOps: Understanding what is MLOps and why is it an important field",
            "Maintainable Code Development: Understanding version control and using tools like Git",
            "Challenges in ML Model Deployment: Overview of ML life cycle stages, challenges in model deployment, approaches to deploying ML models",
            "MLOps Best Practices: Industry standards and guidelines (high level overview of the next 8 weeks)",
            ": Introduction to MLOps",
            "Reality of AI in the market",
            "Introduction",
            "Standard ML Cycle",
            "What is DevOps?",
            "What is MLOPs?",
            "Machine Learning Lifecycle",
            "Introduction to Version Control",
            "Key aspects of Version Control",
            "Types of Version Control Systems",
            "Next two weeks plan",
            ": Version Control",
            "Using GitHub for Version Control",
            "What is GitHub?",
            "Setting Up GitHub",
            "Creating a Repository",
            "Cloning a Repository",
            "Making Changes",
            "Committing Changes",
            "Pushing Changes",
            "Branching",
            "Pull Requests",
            "Collaborating with Others",
            "Revisiting ML Cycle",
            "ML Pipeline Example",
            "Industry Trivia",
            "Doubt Clearance ",
            "Create an Account on GitHub",
            "Github using GUI: VsCode, Github Desktop",
            "Assignment on GitHub Fundamentals",
            "Git Push using CLI",
            "Solving Error: Head is not in Sync",
            "55:10: Touch command"
        ]
    },
    {
        "topic": "ML Reproducibility, Versioning, and Packaging",
        "subtopics": [
            "ML Reproducibility: Ensuring consistent results in ML experiments.",
            "Model Versioning: Tools like MLflow.",
            "Packaging and dependency management: Developing deployable ML packages with dependency management.",
            "Example - DS-cookie-cutter",
            "Data Versioning and Management: Tools like DVC (Data Version Control). [Optional]",
            ": Reproducibility",
            "Story",
            "Industry Tools",
            "Cookiecutter",
            "Step 1: Install the Cookiecutter Library and start a project",
            "Step 2: Explore the Template Structure",
            "Step 3: Customize the Cookiecutter Variables",
            "Step 4: Benefits of Using Cookiecutter Templates in Data Science",
            ": Data Versioning Control",
            "Introduction",
            "Prerequisites",
            "Setup",
            "Step 1: Initialize a Git repository",
            "Step 2: Set up DVC in your project",
            "Step 3: Add a dataset to your project",
            "Step 4: Commit changes to Git",
            "Step 5: Create and version your machine learning pipeline",
            "Step 6: Track changes and reproduce experiments",
            "Doubt Clearance ",
            "Assignment Solution on DVC: 10:19",
            "Doubt Clearance",
            "DVC with G-Drive 42:50",
            "DVC Setup Error: 48:45",
            "Containerization with Virtual Environment 49:40",
            "Create Version and ML Pipeline: 56:50",
            "DVC Checkout 57:50",
            "How to which ID(commit) to go to - through commit messages? 1:00:00",
            "What is Kubernetes?",
            "Not able to understand by reading documentation 1:04:30",
            "Getting no of commits 11k+ 1:09:40"
        ]
    },
    {
        "topic": "End-to-end ML lifecycle management",
        "subtopics": [
            "Setting up MLFlow: Understand MLFlow and its alternatives in depth.",
            "Life cycle components: Projects, model registry, performance tracking.",
            "Best Practices for ML Lifecycle",
            "ML Pipelines and Experimentation Tracking",
            "Doubts",
            "DVC Track by Add",
            "Git clone with SSH vs HTTPS",
            "Recap",
            "Pipelines + DVC + Experimentation Tracking",
            "MLFlow",
            "MLOPs",
            "Recap of Pipelines - Credit Card Example",
            "Writing dvc.yaml File",
            "Reproducibility after Data Changes",
            "Reproducibility after Params Changes",
            "ML end-2-end Pipeline",
            "Tools for different Stages of Pipeline",
            "Doubt Clearance ",
            "Assignment Solution",
            "File not found error - Joblib/Data",
            "Models Not found error",
            "Get familiar With Terminal - DVC –help",
            "DVC Repro vs DVC Exp"
        ]
    },
    {
        "topic": "Containerisation and Deployment Strategies",
        "subtopics": [
            "Containerization: Introduce docker internals and usage.",
            "Distributed infrastructure: Introduce Kubernetes and basic internal components.",
            "Online vs. Offline Model Deployment: Kubernetes for online, and batch processing for offline.",
            "A/B testing.",
            "Canary Deployment and Blue/Green Strategies: Kubernetes, AWS CodeDeploy. [Optional]",
            "Continous Integration",
            "Philosophy Behind CI/CD",
            "Setting UP Github Actions for CI/CD",
            "Workflow setup",
            "Integrating CML for Version Control",
            "Update settings in GitHub Actions",
            "Setting Secret Tokens",
            "Containerisation - Docker",
            "Containerization",
            "Docker"
        ]
    },
    {
        "topic": "DAGs in MLOps",
        "subtopics": [
            "Understanding DAGs in MLOps: Dependency management in ML pipelines.",
            "Building and Managing DAGs: Apache Airflow, Kubeflow Pipelines.",
            "Continuous Integration/ Development: Discuss tools like Github Actions",
            "Continuous Deployment",
            "Recap of Continous Integration",
            "Continuous Delivery/ Deployment",
            "Credit Card Project Code Example",
            "FastApi, pydantic, joblib, uvicorn",
            "How to write app.py",
            "Multi Container",
            "Doubt Clearance ",
            "Assignments Solution"
        ]
    },
    {
        "topic": "Monitoring, Alerting, Retraining, and Rollback",
        "subtopics": [
            "Continuous Monitoring in MLOps: Prometheus, Grafana.",
            "Alerting Systems",
            "Automated Retraining Strategies: Kubeflow Pipelines",
            "Rollback Design Patterns in MLOps: Feature flags, canary releases.",
            "0 - Introduction to AWS",
            "Introduction to AWS Machine Learning and MLOps Services",
            "Pre-requisite",
            "IAM",
            "AWS Sagemaker",
            "Amazon S3",
            "AWS Lambda",
            "Amazon ECR and ECS",
            "AWS CodePipeline and AWS CodeBuild",
            "Components for SageMaker",
            "1 - Deployment on AWS",
            "Code Demo with Credit Card Project",
            "Project Code explained",
            "CI.yml file",
            "Configuring AWS Credentials on GitHub secrets",
            "Creating ECR Repository Getting URI",
            "AWS Region",
            "Pulling ECR repo to EC2 machine",
            "How to create Workflow YML files",
            "Connecting to EC2",
            "Self Runner",
            "AWS Actions"
        ]
    },
    {
        "topic": "Scaling and Efficiency in MLOps",
        "subtopics": [
            "AutoML and Hyperparameter Tuning: AutoML tools (e.g., Google AutoML, Sagemaker Autopilot and Azure AML).",
            "Data Consistency and availability: How offline development becomes a online nightmare",
            "Resource Management and Cost Optimization: Discuss AWS Elastic Kubernetes Service (EKS) Autoscaling, Azure Kubernetes Service (AKS) Autoscale.",
            "2 - Distributed Infrastructure",
            "Understanding Distributed Computing",
            "Node, Communication, and Concurrency",
            "Why Distributed Computing?",
            "Docker and Microservices",
            "Fundamentals of Microservices",
            "Data Bricks Architecture as Microservice",
            "Uber Microservices Architecture",
            "3 on - Kubernetes Internals",
            "What is Kubernetes?",
            "Need of Kubernetes: Container orchestration system",
            "Key Concepts",
            "Pods",
            "Nodes",
            "Cluster",
            "Control Panel",
            "API Server",
            "Resource Manager",
            "Database",
            "Deployment",
            "Deploying with Kubectl"
        ]
    },
    {
        "topic": "Final Project",
        "subtopics": [
            "Implementing a Full MLOps Pipeline for a Real-World Use Case Locally",
            "4 - Deployment on Kubernetes",
            "Deployment with Kubectl",
            "Explained Deployment yml file",
            "Deployment Demo",
            "Deployment Strategies",
            "Service and Load Balancing",
            "5 - Seldon Deployments",
            "Introduction to Sheldon",
            "Key Features of Sheldon",
            "Sheldon vs Competitors",
            "Pre-Requisite: Kubectl and helm",
            "Deployment",
            "Step 1: Install Seldon Core using Helm",
            "Step 2: Define a Simple Machine Learning Model",
            "Step 3: Push your model to S3 or Google store",
            "Step 4: Define a Seldon Deployment",
            "Step 5: Deploy the Seldon Deployment",
            "Seldon vs EKS vs K8s",
            "Kubeflow Pipelines",
            "KubeFlow Pipeline Overview with MNIST Dataset",
            "Apache Airflow"
        ]
    },
    {
        "topic": "ML Technical Debt",
        "subtopics": [
            "Understanding and Managing ML Technical Debt: Identifying and addressing technical debt in ML projects.",
            "6 - Monitoring & Alerting",
            "7 - Rollout & Rollback Strategies",
            "8 - ML Technical Debt"
        ]
    },
    {
        "topic": "Unsupervised Learning",
        "subtopics": [
            "KMeans Clustering",
            " KMeans Clustering",
            "Plan of Attack (Getting Started with Clustering)",
            "Types of ML Learning",
            "Applications of Clustering",
            "Geometric Intuition of K-Means",
            "Elbow Method for Deciding Number of Clusters",
            "Code Example",
            "Limitation of Elbow Method",
            "Assumptions of KMeans",
            "Limitations of K Means",
            "KMeans Clustering",
            "Recap of Last class",
            "Assignment Solution",
            "Silhouette Score",
            "Kmeans Hyperparameters",
            "Number of Clusters(k)",
            "Initialization Method (K Means++)",
            "Number of Initialization Runs (n_init)",
            "Maximum Number of Iterations (max_iter)",
            "Tolerance (tol)",
            "Algorithm (auto, full, ..)",
            "Random State",
            "K Means ++",
            "KMeans Clustering",
            "K-Means Mathematical Formulation (Loyd’s Algorithm)",
            "K-Means Time and Space Complexity",
            "Mini Batch K Means",
            "Types of Clustering",
            "Partitional Clustering",
            "Hierarchical Clustering",
            "Density Based Clustering",
            "Distribution/Model-based Clustering",
            "K-Means Clustering Algorithms from Scratch in Python",
            "Algorithms implementation from Scratch in Python",
            "Other Clustering Algorithms",
            "DBSCAN",
            "Why DBSCAN?",
            "What is Density Based Clustering",
            "MinPts & Epsilon",
            "Core Points, Border Points & Noise Points",
            "Density Connected Points",
            "DBSCAN Algorithm",
            "Code",
            "Limitations",
            "Visualization",
            "Hierarchical Clustering",
            "Need of Other Clustering Methods",
            "Introduction",
            "Algorithm",
            "Types of Agglomerative Clustering",
            "Min (Single-link)",
            "Max (Complete Link)",
            "Average",
            "Ward",
            "How to find the ideal number of clusters",
            "Hyperparameter",
            "Code Example",
            "Benefits/Limitations",
            "Gaussian Mixture Models (GMM)",
            "The Why?",
            "The What?",
            "Geometric Intuition",
            "Multivariate Normal Distribution",
            "Geometric Intuition 2D",
            "EM(Expectation Minimization) Algorithm",
            "Python Code",
            "Gaussian Mixture Models",
            "Recap of ",
            "Covariance Types: Spherical, Diagonal, Full, and Tied",
            "How to decide n_components?",
            "Akaike Information Criterion (AIC)",
            "Bayesian Information Criterion(BIC)",
            "Likelihood Formula for GMM",
            "Python Implementation.",
            "Why not Silhouette Score?",
            "Visualization",
            "Assumptions",
            "Advantages & Disadvantages",
            "K Means vs GMM",
            "DBSCAN vs GMM",
            "Applications of GMM",
            "T-SNE",
            "What is T-SNE?",
            "Why learn T-SNE?",
            "Geometric Intuition",
            "Mathematical Formulation",
            "Code Implementation",
            "T-SNE",
            "Mathematical Formulation",
            "Some Questions!",
            "Why use probabilities instead of distances to calculate similarity?",
            "Why use Gaussian distribution to calculate similarity in high dimensions?",
            "How is variance calculated for each Gaussian distribution?",
            "Why use T-distribution in lower dimensions?",
            "Code Example",
            "Hyperparameters",
            "Perplexity",
            "Learning Rate",
            "Number of Iterations",
            "Points of Wisdom",
            "Advantages & Disadvantages",
            "LDA (Linear Discriminant Analysis)",
            "Introduction: Supervised dimensionality reduction",
            "Algorithm Explanation: Maximizing between-class variance",
            "Applications: Use cases in classification and visualization",
            "Comparison: Differences and similarities with PCA",
            "Apriori",
            "Introduction: Principles of association rule mining",
            "Key Concepts: Support, Confidence, Lift",
            "Algorithm Steps: Candidate generation, Pruning",
            "Applications: Market Basket Analysis, Recommender Systems",
            "UMAP (Uniform Manifold Approximation and Projection)",
            "Introduction: Overview of the algorithm",
            "Key Concepts: Topological Structures, Nearest Neighbors",
            "Applications: Dimensionality reduction, Visualization",
            "Comparison: Differences and similarities with t-SNE and PCA"
        ]
    },
    {
        "topic": "Competitive Data Science",
        "subtopics": [
            "Adaboost",
            "Introduction: Overview and intuition of the algorithm",
            "Components: Weak Learners, Weights, Final Model",
            "Hyperparameters: Learning Rate, Number of Estimators",
            "Applications: Use Cases in Classification and Regression",
            "Stacking",
            "Introduction: Concept of model ensembling",
            "Steps: Base Models, Meta-Model, Final Prediction",
            "Variations: Different approaches and modifications",
            "Best Practices: Tips for effective stacking",
            "LightGBM",
            "Introduction: Gradient boosting framework",
            "Key Features: Handling large datasets, Categorical feature support",
            "Parameters: Core hyperparameters and their tuning",
            "Applications: Common use cases and performance considerations",
            "CatBoost",
            "Introduction: Categorical boosting algorithm",
            "Handling Categorical Features: Algorithmic approach",
            "Key Parameters: Learning Rate, Depth, Iterations",
            "Practical Usage: Tips and common practices",
            "Advanced Hyperparameter Tuning",
            "Strategies: Bayesian Optimization",
            "Libraries: Optuna, Hyperopt",
            "Practical Tips: Efficient tuning, Avoiding overfitting",
            "Evaluation: Ensuring robust model performance",
            "Participating in a real Kaggle Competition",
            "Getting Started: Understanding the problem, Exploring datasets",
            "Strategy: Model selection, Preprocessing, Validation",
            "Collaboration: Teamwork, Sharing, and Learning",
            "Submission and Evaluation: Making effective submissions, Learning from feedback"
        ]
    },
    {
        "topic": "Miscellaneous Topics",
        "subtopics": [
            "NoSQL",
            "Introduction: Overview of NoSQL databases",
            "Types: Document, Key-Value, Column-Family, Graph",
            "Use Cases: When to use NoSQL over SQL databases",
            "Popular Databases: MongoDB, Cassandra, Redis, Neo4j",
            "Model Explainability",
            "Introduction: Importance of interpretable models",
            "Techniques: LIME, SHAP, Feature Importance",
            "Application: Applying techniques to various models",
            "Best Practices: Ensuring reliable and accurate explanations",
            "AutoML",
            "Introduction: Automated machine learning overview",
            "Platforms: Google AutoML, H2O.ai, DataRobot",
            "Capabilities: Data preprocessing, Model selection, Hyperparameter tuning",
            "Evaluation: Assessing AutoML performance and reliability",
            "FastAPI",
            "Introduction: Modern, fast web framework for building APIs",
            "Features: Type checking, Automatic validation, Documentation",
            "Building APIs: Steps and best practices",
            "Deployment: Hosting and scaling FastAPI applications",
            "AWS Sagemaker",
            "Introduction: Fully managed service for machine learning",
            "Features: Model building, Training, Deployment",
            "Usage: Workflow from data preprocessing to model deployment",
            "Best Practices: Optimizing costs and performance",
            "Handling Imbalanced Data",
            "Introduction: Challenges of imbalanced datasets",
            "Techniques: Resampling, SMOTE, Using different evaluation metrics",
            "Algorithms: Choice of algorithms for imbalanced data",
            "Best Practices: Ensuring robust and unbiased models",
            "Online Machine Learning",
            "Introduction: Machine learning on streaming data",
            "Algorithms: Suitable algorithms for online learning",
            "Challenges: Handling concept drift, Scalability",
            "Application: Real-time learning and prediction use cases"
        ]
    }
]