name: Python Cron Jobs

on:
  schedule:
    - cron: '0 0 * * *'        # run_post_generation.py at 12:00 AM daily
    - cron: '5 9 * * *'        # run_publish_tweet.py at 09:05 AM
    - cron: '35 12 * * *'      # run_publish_tweet.py at 12:35 PM
    - cron: '5 16 * * *'       # run_publish_tweet.py at 04:05 PM
    - cron: '35 19 * * *'      # run_publish_tweet.py at 07:35 PM
  workflow_dispatch:

jobs:
  run-cron-tasks:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_SECRET: ${{ secrets.X_API_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      DB_URL: ${{ secrets.DB_URL }}
      X_USERNAME: ${{ secrets.X_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run run_post_generation.py at 12:00 AM
        if: github.event.schedule == '0 0 * * *'
        run: python scripts/run_post_generation.py

      - name: Run run_publish_tweet.py at scheduled times
        if: |
          github.event.schedule == '5 9 * * *' ||
          github.event.schedule == '35 12 * * *' ||
          github.event.schedule == '5 16 * * *' ||
          github.event.schedule == '35 19 * * *'
        run: python scripts/run_publish_tweet.py
