name: Post Generation

on:
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      DB_URL: ${{ secrets.DB_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python scripts/run_post_generation.py
