name: Tweet Publisher

on:
  schedule:
    - cron: '35 2 * * *'     # 08:05 AM IST
    - cron: '35 4 * * *'     # 10:05 AM IST
    - cron: '5 7 * * *'      # 12:35 PM IST
    - cron: '35 8 * * *'     # 02:05 PM IST
    - cron: '35 10 * * *'    # 04:05 PM IST
    - cron: '35 12 * * *'    # 06:05 PM IST
    - cron: '5 14 * * *'     # 07:35 PM IST
    - cron: '5 15 * * *'     # 08:35 PM IST
    - cron: '25 17 * * *'    # 10:55 PM IST
    - cron: '35 17 * * *'    # 11:05 PM IST
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_SECRET: ${{ secrets.X_API_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      DB_URL: ${{ secrets.DB_URL }}
      X_USERNAME: ${{ secrets.X_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: python scripts/run_publish_tweet.py
